### ISSUE TITLE
mesh_m _ell _ 05.txt

### ISSUE THREAD

**Issue by vaswdscdas** [wqfang/FEA-PhaseFieldMethod#1]
Hello,

"File \!\(\"**mesh_m_ell_05.txt**\"\) not found during Import"

Also:

ReadList::stream: $Failed is not a string, SocketObject, InputStream[ ], or OutputStream[ ].
Counts::invl: The argument ReadList[$Failed,String] is not a list.

Best

**Comment by wqfang** [comment]
I was testing my code using external mesh. You can try to use your own mesh file or build a mesh inside Mathematica.
